name: Check URLs
on:
  push:
  pull_request:
  schedule:
    - cron: '0 10 * * *'
jobs:
  check_urls:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: urls-checker
      uses: urlstechie/urlchecker-action@0.2.3
      with:
        include_files: "README.md,urls.md"
